# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: ci-pools-2
  # vmImage: ubuntu-latest

stages:
   - stage: check
     displayName: Check Directory Struct
     jobs:
       - job:
         displayName: Check container images
         container:
           image: nginx
         steps:
         - script: |
             cat /etc/os-release
             ls -hl
             curl ifconfig.io
             # which gcloud
             # which aws
             # which az
            
   # - stage: check
   #   displayName: Check Directory Struct
   #   jobs:
   #     - job:
   #       steps:
   #       - script: |
   #           echo "Hello, World!"
   #         displayName: 'Print Hello World'
   #     - job:
   #       steps:
   #       - script: |
   #           ls -hl
   #         displayName: 'List Directory'

  # - stage: check2
  #   displayName: Check agent egress IP
  #   jobs:
  #     - job:
  #       steps:
  #       - script: |
  #           curl -s ifconfig.io
  #         displayName: 'Get Egress IP Address'
  
  # - stage: check3
  #   displayName: Check OS info
  #   jobs:
  #     - job:
  #       steps:
  #       - script: |
  #           cat /etc/os-release
  #         displayName: 'Get OS Info'
