# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

# resources:
#   containers:
#   - container: cloud-tools
#     type: ACR
#     azureSubscription: diver
#     resourceGroup: DIVER
#     registry: diver.azurecr.io
#     repository: internal/docker-kubectl
#     trigger:
#       tags:
#         - v1.0

pool:
  name: ci-agents
  # vmImage: ubuntu-latest

stages:
  - stage: check
    displayName: Check Directory Struct
    jobs:
      - job:
        displayName: Check container images
        container:
          image: diver.azurecr.io/internal/docker-kubectl:v1.0
        steps:
        - script: |
            cat /etc/os-release
            ls -hl
            which gcloud
            which aws
            which az
            
  # - stage: check
  #   displayName: Check Directory Struct
  #   jobs:
  #     - job:
  #       steps:
  #       - script: |
  #           echo "Hello, World!"
  #         displayName: 'Print Hello World'
  #     - job:
  #       steps:
  #       - script: |
  #           ls -hl
  #         displayName: 'List Directory'

  # - stage: check2
  #   displayName: Check agent egress IP
  #   jobs:
  #     - job:
  #       steps:
  #       - script: |
  #           curl -s ifconfig.io
  #         displayName: 'Get Egress IP Address'
  
  # - stage: check3
  #   displayName: Check OS info
  #   jobs:
  #     - job:
  #       steps:
  #       - script: |
  #           cat /etc/os-release
  #         displayName: 'Get OS Info'
