# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: demo-pool-4
  # vmImage: ubuntu-latest

stages:
  - stage: loginAzure
    displayName: Login Azure
    jobs:
      - job:
        displayName: login
        steps:
          - task: AzureCLI@2
            displayName: Login to Azure
            inputs:
              azureSubscription: ci-vmss-azure-subscription
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az acr login --name diver
            
  - stage: loginACR
    displayName: Login ACR
    jobs:
      - job:
        displayName: Check container images
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              containerRegistry: ci-vmss-acr
              command: 'login'
          
  - stage: pullImages
    displayName: pull Images
    jobs:
      - job:
        displayName: pull images
        steps:
          - script: |
              docker pull diver.azurecr.io/internal/docker-kubectl:v1.0
            displayName: 'pull images'
              
  - stage: checkCredentials
    displayName: Check Credentials
    jobs:
      - job:
        displayName: Check credentials
        steps:
          - task: DownloadSecureFile@1
            name: googleArtifactRegistryKey
            inputs:
              secureFile: gke-artifact-registry-rw.json
          - script: |
              cat $(googleArtifactRegistryKey.secureFilePath)
            displayName: 'Check Credentials'
              
  - stage: checkTools
    displayName: Check Tools
    jobs:
      - job:
        steps:
          - script: |
              which gcloud
              which aws
              which az
              which kustomize
              which helm
              which kubectl
              gcloud version
            displayName: 'Check Tools'
            
  - stage: checkDirectoryStruct
    displayName: Check Directory Struct
    jobs:
      - job:
        steps:
        - script: |
            ls -hl
          displayName: 'List Directory'

  # - stage: checkAgentEgressIP
  #   displayName: Check agent egress IP
  #   jobs:
  #     - job:
  #       steps:
  #       - script: |
  #           curl -s ifconfig.io
  #         displayName: 'Get Egress IP Address'

  # - stage: checkOSInfo
  #   displayName: Check OS info
  #   jobs:
  #     - job:
  #       steps:
  #       - script: |
  #           cat /etc/os-release
  #         displayName: 'Get OS Info'
